name: SafeRoPE

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10.18
  - pip=25.2
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - transformers==4.56.1
      - diffusers==0.35.1
      - accelerate==1.10.1
      - huggingface-hub==0.35.0
      - safetensors==0.6.2
      - tokenizers==0.22.0
      - sentencepiece==0.2.1
      - numpy==2.2.6
      - pillow==11.3.0
      - opencv-python==4.12.0.88
      - matplotlib==3.10.6
      - invisible-watermark==0.2.0
      - pywavelets==1.8.0
      - einops==0.8.1
      - fire==0.7.1
      - pyyaml==6.0.2
      - requests==2.32.5
      - gradio==5.13.2
      - streamlit==1.49.1
      - streamlit-drawable-canvas==0.9.3
      - streamlit-keyup==0.3.0
      - fastapi==0.116.2
      - uvicorn==0.35.0
      - python-multipart==0.0.20
      - ruff==0.6.8